name: Update docs-map.json

on:
  push:
    branches:
      - main

jobs:
  update-docs-map:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run update_docs_map.py script
        run: python blogs/update_docs_map.py
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add blogs/docs-map.json
          git commit -m "Update docs-map.json" || echo "No changes to commit"
          git push
